### ISSUE TITLE
HyPhy version 2.3.4 - Error running python-HyPhy module: batch file requires at least version 2.3.3

### ISSUE THREAD

**Issue by franzileo** [veg/hyphy-python#1]
Dear Developers,

I have the HyPhy package (version 2.3.4) and HyPhy-Python module (installed one week ago, seems to be version 2.0.4) installed.

I tested the BasicHyPhy.py file and it's working, however when I actually try executing a batch file to run a analzsis of the HyPhy package (e.g. MEME.bf) I get this error (hyphyerrors.sData):
Current batch file requires at least version :2.3.3 of HyPhy. Please download an updated version from http://www.hyphy.org and try again. in call to RequireVersion(')

Do you have any idea what could be the problem here?
I can only guess that the 'Require Version' comes from the MEME.bf file. Might there be an incompatibility between hyphy-python and the actual hyphy package since hyphy-python was last updated one year ago?

Thanks a lot in advance!
Best,
Franziska

**Comment by stevenweaver** [comment]
Dear Franziska, 

There is indeed an incompatibility at the moment. I've moved this issue up in priority, but it still may take a bit of time before hyphy-python is fully updated.

Best,
Steven
