### ISSUE TITLE
ld: library not found for -lssl

### ISSUE THREAD

**Issue by mdhall272** [veg/hyphy-python#2]
When trying to install hyphy-python on Mac OS (10.14.4), I get the following error:

```
python3.7 setup.py install
...
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```

I've tried uninstalling openssl and installing libressl instead without any success. It works with python 3.6.

**Comment by stevenweaver** [comment]
Hi @mdhall272, 

I've confirmed the issue. Thanks for bringing this to our attention. I'm working on a resolution now. 

Best,
Steven

**Comment by stevenweaver** [comment]
Hi @mdhall272, 

Assuming you are using homebrew. You can set your environment variable like so:

`export LIBRARY_PATH=/usr/local/Cellar/openssl@1.1/1.1.1b/lib:$LIBRARY_PATH`

The change appears to be with how Python 3.7 is constructing the linking statement. In the past, python was smart enough to find and add `-L` flags like `-L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib` to the linking statement. 

In Python 3.7, these flags have vanished. Using environment variables will help for now, but I'll see if I can add the appropriate flags in `setup.py` for posterity's sake.

Best,
Steven
